export const images = {
    appLogo: require('@assets/images/logo.jpg'),
    avatar: require('@assets/images/avatar.png'),
    avatar2: require('@assets/images/avatar2.png'),
    avatar3: require('@assets/images/avatar3.png'),
    avatar4: require('@assets/images/avatar4.jpg'),
    avatar5: require('@assets/images/avatar5.jpg'),
    avatar6: require('@assets/images/avatar6.jpg'),
    avatar7: require('@assets/images/avatar7.jpg'),
    avatar8: require('@assets/images/avatar8.jpg'),
    avatar9: require('@assets/images/avatar9.jpg'),
    avatar10: require('@assets/images/avatar10.jpg'),
    crypto: require('@assets/images/crypto.png'),
    pexels1: require('@assets/images/pexels1.jpg'),
    pexels2: require('@assets/images/pexels2.jpg'),
    pexels3: require('@assets/images/pexels3.jpg'),
    pexels4: require('@assets/images/pexels4.jpg'),
    pexels5: require('@assets/images/pexels5.jpg'),
    pexels6: require('@assets/images/pexels6.jpg'),
    pexels7: require('@assets/images/pexels7.jpg'),
    pexels8: require('@assets/images/pexels8.jpg'),
    pexels9: require('@assets/images/pexels9.jpg'),
    pexels10: require('@assets/images/pexels10.jpg'),
    pexels11: require('@assets/images/pexels11.jpg'),
    pexels12: require('@assets/images/pexels12.jpg'),

}